train:
  _target_: src.datasets.ASVspoofDataset
  name: "train"
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.ASVspoofDataset
  name: "test"
  instance_transforms: ${transforms.instance_transforms.inference}
