val:
  _target_: src.datasets.ASVspoofDataset
  input_length: 1024
  dataset_length: 15
  n_classes: 2
  name: "val"
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.ASVspoofDataset
  input_length: 1024
  dataset_length: 15
  n_classes: 2
  name: "test"
  instance_transforms: ${transforms.instance_transforms.inference}
